version: '3'
services:
  app_a:
    build: .
    depends_on:
      - localstack
    entrypoint: /bin/bash
    command: "gradlew run --args 'queuea queueb'"
    restart: unless-stopped
    networks:
      - net

  app_b:
    build: .
    depends_on:
        - localstack
    entrypoint: /bin/bash
    command: "gradlew run --args 'queueb queuea'"
    restart: unless-stopped
    networks:
        - net

  localstack:
    image: localstack/localstack
    command: bash -c "aws —endpoint-url=http://localhost:4576 sqs create-queue —queue-name queuea && aws —endpoint-url=http://localhost:4576 sqs create-queue —queue-name queueb"
    ports:
      - "4576:4576"
    environment:
      - SERVICES=sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    networks:
      - net

networks:
    net:
        driver: "bridge"